import Image from "next/image";
import Head from "next/head";
import { useState } from "react";

import { AiOutlinePlus, AiOutlineCompress } from "react-icons/ai";
import styled from "styled-components";
import NewTimerForm from "../components/Form";
import { AnimatePresence } from "framer-motion";
import { useTimerData } from "../context/Timer";
import { useRouter } from "next/router";

export const Main = styled.main`
  position: relative;
  overflow: hidden;

  height: 100vh;
  display: grid;
  place-content: center;

  .main-bg {
    position: fixed;
    inset: 0;
    z-index: -1;
    height: 100vh;
    width: 100vw;
    object-fit: cover;
    object-position: bottom center;

    filter: blur(6px);
    -webkit-filter: blur(6px);
    transform: scale(1.025);
  }
`;

const OptionWrapper = styled.div`
  display: flex;
  flex-direction: column;
  gap: 1rem;

  @media (min-width: 425px) {
    flex-direction: row;
  }

  .option {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1rem;

    border-radius: 5px;
    padding: 2rem 1.5rem;
    min-width: 170px;
    cursor: pointer;

    background-color: ${({ theme }) => theme.primary};
    font-weight: 500;
    color: ${({ theme }) => theme.faded};
    box-shadow: ${({ theme }) => theme.shadowPrimary};
    transition: all 0.2s ease-in-out;

    &:hover {
      transform: scale(1.05);
    }

    .icon {
      font-size: 1.75rem;
      color: ${({ theme }) => theme.accent};
    }
  }
`;

export default function Home() {
  const router = useRouter();
  const [isFormOpen, setIsFormOpen] = useState(false);

  const closeForm = () => {
    setIsFormOpen(false);
  };

  const data = useTimerData();

  return (
    <>
      <Head>
        <title>Pomodoro | Tasks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>💀</text></svg>"
        />
      </Head>
      <Main>
        <Image
          priority
          src={data.ambience.imagePath || "/images/waves-beach.gif"}
          height={100}
          width={400}
          alt=""
          className="main-bg"
        />

        <OptionWrapper>
          <div className="option" onClick={() => router.push("/pomodoro")}>
            <span>
              <AiOutlineCompress className="icon" />
            </span>
            <span>Use Preset</span>
          </div>
          <div className="option" onClick={() => setIsFormOpen(true)}>
            <span>
              <AiOutlinePlus className="icon" />
            </span>
            <span>Add New</span>
          </div>
        </OptionWrapper>
        <AnimatePresence mode="wait">
          {isFormOpen && <NewTimerForm closeForm={closeForm} />}
        </AnimatePresence>
      </Main>
    </>
  );
}
